
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 30 06:44:55 PST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HEXINT = 25;
  public static final int TIMES = 6;
  public static final int MOD = 8;
  public static final int AND = 19;
  public static final int BNOT = 23;
  public static final int PLUS = 2;
  public static final int OR = 20;
  public static final int RPAREN = 13;
  public static final int EQUAL = 10;
  public static final int SEMI = 14;
  public static final int BININT = 26;
  public static final int NOT = 18;
  public static final int POW = 9;
  public static final int LPAREN = 12;
  public static final int INC = 3;
  public static final int CMP = 17;
  public static final int EOF = 0;
  public static final int PRINTLN = 16;
  public static final int DIV = 7;
  public static final int BOR = 21;
  public static final int str = 30;
  public static final int DEC = 5;
  public static final int MINUS = 4;
  public static final int PRINT = 15;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int INTEGER = 24;
  public static final int REAL = 28;
  public static final int BAND = 22;
  public static final int FRACTION = 27;
  public static final int VAR = 29;
}

